substitutions:
  # all substitutions for this project
  friendly_name: Tesla BLE
  device_name: tesla-ble
  device_description: Tesla BLE
  ble_mac_address: !secret ble_mac_address
  tesla_vin: !secret tesla_vin
  charging_amps_max: "32"

esp32:
  board: esp32dev  # set as needed for your board
  framework:
    type: esp-idf

api:
  encryption:
    key: xxxxxxxxxxxxx= # use "key: !secret your_secret_key_name" for greater security

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  source: github://PedroKTFC/esphome-tesla-ble

packages:
  base:  github://PedroKTFC/esphome-tesla-ble/packages/base.yml
  common: github://PedroKTFC/esphome-tesla-ble/packages/common.yml
  project: github://PedroKTFC/esphome-tesla-ble/packages/project.yml
  client: github://PedroKTFC/esphome-tesla-ble/packages/client.yml
  # listener: github://PedroKTFC/esphome-tesla-ble/packages/listener.yml # Uncomment this to scan find your VIN BLE MAC address

esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git

tesla_ble_vehicle:
  odometer: # miles by default, edit the entity in home assistant if you need km
    name: "Odometro" # Rename if desired
# At the time of writing, these are set to the default values. If you require a different value, uncomment and edit the value
#  update_interval: 2s # Base polling interval, used for VCSEC sensors
#  post_wake_poll_time: 300 # How long to poll for data after car awakes (s)
#  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
#  poll_charging_period: 2 # Period to poll for data when charging (s)
#  poll_asleep_period: 60 # Period to poll for data when asleep (s)
