substitutions:
  device_description: Interact with Tesla vehicles over BLE using ESPHome and Home Assistant

esphome:
  project:
    name: PedroKTFC.esphome-tesla-ble
    version: "2025.1.3"

logger:
  level: INFO

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret wifi_hotspot_password
