substitutions:
  ble_mac_address: !secret ble_mac_address
  tesla_vin: !secret tesla_vin
  charging_amps_max: "32"

ble_client:
  - mac_address: $ble_mac_address
    id: ble_tesla_id

# Tesla BLE Vehicle - automatically creates all entities based on role
tesla_ble_vehicle:
  ble_client_id: ble_tesla_id
  id: tesla_ble_vehicle_id
  vin: $tesla_vin
  update_interval: 1min
  charging_amps_max: $charging_amps_max
  role: DRIVER  # Options: DRIVER (all controls) or CHARGING_MANAGER (charging + basic controls only)

# BLE sensors from the standard ble_client platform
sensor:
  - platform: ble_client
    type: rssi
    ble_client_id: ble_tesla_id
    name: "BLE Signal"
    icon: mdi:bluetooth
    update_interval: 60s
    entity_category: diagnostic

switch:
  - platform: ble_client
    ble_client_id: ble_tesla_id
    name: "BLE Connection"
    entity_category: diagnostic