substitutions:
  ble_mac_address: !secret ble_mac_address
  tesla_vin: !secret tesla_vin
  charging_amps_max: "32"

ble_client:
  - mac_address: $ble_mac_address
    id: ble_tesla_id

tesla_ble_vehicle:
  ble_client_id: ble_tesla_id
  id: tesla_ble_vehicle_id
  vin: $tesla_vin
  update_interval: 10s # default
  post_wake_poll_time: 300 # How long to poll for data after car awakes (s)
  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
  poll_asleep_period: 60 # Period to poll for data when asleep (s)
  poll_charging_period: 10 # Period to poll for data when charging (s)
  ble_disconnected_min_time: 300 # Minimum time BLE must be disconnected before sensors are Unknwon (s)
  fast_poll_if_unlocked: 1 # if != 0, fast polls are enabled when unlocked

  is_asleep:
    name: "Asleep"
  is_user_present:
    name: "User presence"
  is_unlocked:
    id: "is_unlocked"
    name: "Doors"
  is_charge_flap_open:
    id: "is_charge_flap_open"
    name: "Charge flap"
  is_boot_open:
    id: "is_boot_open"
    name: "Boot"
  is_frunk_open:
    id: "is_frunk_open"
    name: "Frunk"
  shift_state:
    name: "Shift state"
  defrost_state:
    id: "defrost_state"
    name: "Defrost state"
  charge_state:
    id: "charge_state"
    name: "Charge level"
  odometer:
    name: "Odometer"
    filters:
      - multiply: 0.01 # Odometer is in hundredths of a mile (can use this to convert to km)
  charge_current:
    id: "charge_current"
    name: "Charge current"
  charge_voltage:
    id: "charge_voltage"
    name: "Charge voltage"  
  charge_power:
    id: "charge_power"
    name: "Charge power"
  charge_energy_added:
    id: "charge_energy_added"
    name: "Charge energy added"
  charge_distance_added:
    id: "charge_distance_added"
    name: "Charge distance added"
  max_soc:
    id: "max_soc"
    name: "Charge limit"
  max_amps:
    id: "max_amps"
    name: "Current limit"
  mins_to_limit:
    id: "mins_to_limit"
    name: "Minutes to limit"
  battery_range:
    name: "Range"
  charging_state:
    id: "charging_state"
    name: "Charging state"
  last_update:
    name: "Last update"
  is_climate_on:
    id: "is_climate_on"
    name: "Climate"
  internal_temp:
    name: "Interior"
  external_temp:
    name: "Exterior"
  windows_state:
    id: "windows_state"
    name: "Windows"
      
button:
  - platform: template
    id: ble_pair
    name: Pair BLE key
    icon: mdi:key-wireless
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->startPair();
    entity_category: diagnostic

  - platform: template
    name: Wake up
    icon: mdi:sleep-off
    on_press:
    - lambda: id(tesla_ble_vehicle_id)->wakeVehicle();

  - platform: template
    name: Flash light
    icon: mdi:car-light-high
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage (FLASH_LIGHT, 0);

  - platform: template
    name: Sound horn
    icon: mdi:bugle
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage (SOUND_HORN, 0);

  - platform: template
    name: Unlock charge port
    icon: mdi:ev-plug-ccs2
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->sendVCSECClosureMoveRequestMessage (VCSEC_ClosureMoveRequest_chargePort_tag, VCSEC_ClosureMoveType_E_CLOSURE_MOVE_TYPE_OPEN);

  - platform: template
    name: Unlatch driver door
    icon: mdi:car-door
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->sendVCSECClosureMoveRequestMessage (VCSEC_ClosureMoveRequest_frontDriverDoor_tag, VCSEC_ClosureMoveType_E_CLOSURE_MOVE_TYPE_OPEN);
    disabled_by_default: true

  - platform: template
    name: Regenerate key
    icon: mdi:key-change
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->regenerateKey();
    entity_category: diagnostic
    disabled_by_default: true

  - platform: template
    name: Force data update
    icon: mdi:database-sync
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->enqueueVCSECInformationRequest(true);
    entity_category: diagnostic

sensor:
  - platform: ble_client
    type: rssi
    id: ble_signal
    ble_client_id: ble_tesla_id
    name: "BLE Signal"
    icon: mdi:bluetooth
    update_interval: 60s
    entity_category: diagnostic

switch:
  - platform: template
    name: "Charger"
    optimistic: true
    icon: mdi:lightning-bolt
#    restore_mode: RESTORE_DEFAULT_OFF
    lambda: |-
      if ((id(charging_state).state == "Charging") or (id(charging_state).state == "Starting") or (id(charging_state).state == "Calibrating")) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_CHARGING_SWITCH, 1);
    turn_off_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_CHARGING_SWITCH, 0);

  - platform: template
    name: "Sentry mode"
    optimistic: true
    icon: mdi:record-circle-outline
    assumed_state: true # we can't read the state 
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_SENTRY_SWITCH, 1);
    turn_off_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_SENTRY_SWITCH, 0);
  
  - platform: template
    name: "Climate"
    optimistic: true
    icon: mdi:fan
    lambda: |-
      if (id(is_climate_on).state) {
        return true;
      } else {
        return false;
      }
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_HVAC_SWITCH, 1);
    turn_off_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_HVAC_SWITCH, 0);

  - platform: template
    name: "Steering wheel heat"
    optimistic: true
    icon: mdi:steering
    assumed_state: true # we can't read the state 
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_HVAC_STEERING_HEATER_SWITCH, 1);
    turn_off_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_HVAC_STEERING_HEATER_SWITCH, 0);
  
  - platform: template
    name: Defrost car
    optimistic: true
    icon: mdi:snowflake-melt
    lambda: |-
      if (id(defrost_state).state != "Off") {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage (DEFROST_CAR, 1);
    turn_off_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage (DEFROST_CAR, 0);
      
  - platform: ble_client
    ble_client_id: ble_tesla_id
    name: "BLE Connection"
    entity_category: diagnostic

lock:
  - platform: template
    name: "Lock car"
    optimistic: true
    icon: mdi:lock
    lambda: |-
      if (id(is_unlocked).state) {
          return LOCK_STATE_UNLOCKED;
        } else {
          return LOCK_STATE_LOCKED;
        }
    unlock_action:
      - lambda: |-
          id(tesla_ble_vehicle_id)->lockVehicle(VCSEC_RKEAction_E_RKE_ACTION_UNLOCK);
    lock_action:
      - lambda: |-
          id(tesla_ble_vehicle_id)->lockVehicle(VCSEC_RKEAction_E_RKE_ACTION_LOCK);

cover:
  - platform: template
    name: "Vent"
    optimistic: false #### true
    icon: mdi:car-door
    device_class: door
    lambda: |-
      if (id(windows_state).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    close_action: #### This way round to make the arrows follow the desired window motion
      - lambda: |-
          id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage (SET_WINDOWS_SWITCH, 0);
    open_action:
      - lambda: |-
          id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage (SET_WINDOWS_SWITCH, 1);

  - platform: template
    name: "Charge port"
    optimistic: true
    device_class: door
    icon: mdi:ev-plug-ccs2
    lambda: |-
      if (id(is_charge_flap_open).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
#    restore_mode: RESTORE_DEFAULT_OFF
    open_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_OPEN_CHARGE_PORT_DOOR,1);
    close_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_CLOSE_CHARGE_PORT_DOOR,1);
  
  - platform: template
    name: "Boot"
    optimistic: true
    device_class: door
    icon: mdi:car-back
    lambda: |-
      if (id(is_boot_open).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
#    restore_mode: RESTORE_DEFAULT_OFF
    open_action:
      - lambda: id(tesla_ble_vehicle_id)->sendVCSECClosureMoveRequestMessage (VCSEC_ClosureMoveRequest_rearTrunk_tag, VCSEC_ClosureMoveType_E_CLOSURE_MOVE_TYPE_OPEN);
    close_action:
      - lambda: id(tesla_ble_vehicle_id)->sendVCSECClosureMoveRequestMessage (VCSEC_ClosureMoveRequest_rearTrunk_tag, VCSEC_ClosureMoveType_E_CLOSURE_MOVE_TYPE_CLOSE);

  - platform: template
    name: "Frunk"
    optimistic: true
    device_class: door
    icon: mdi:car
#    assumed_state: true # we can't read the state 
    lambda: |-
      if (id(is_frunk_open).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - lambda: id(tesla_ble_vehicle_id)->sendVCSECClosureMoveRequestMessage (VCSEC_ClosureMoveRequest_frontTrunk_tag, VCSEC_ClosureMoveType_E_CLOSURE_MOVE_TYPE_OPEN);
    
number:
  - platform: template
    name: "Charging amps"
    id: charging_amps
    icon: mdi:ev-station
    unit_of_measurement: "A"
    mode: slider
    update_interval: 2s
    min_value: 0
    max_value: $charging_amps_max
    step: 1
    set_action:
      - lambda: |-
          int var_x = static_cast<int>(x);
          id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_CHARGING_AMPS, var_x);
    lambda: |-
      if (id(max_amps).has_state())
      {
        return id(max_amps).state;
      }
      else return (0);
  - platform: template
    name: "Charging limit"
    id: charging_limit
    icon: mdi:ev-station
    unit_of_measurement: "%"
    mode: slider
    update_interval: 2s
    min_value: 50
    max_value: 100
    step: 1
    set_action:
      - lambda: |-
          int var_x = static_cast<int>(x);
          id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_CHARGING_LIMIT, var_x);
    lambda: |-
      if (id(max_soc).has_state())
      {
        return id(max_soc).state;
      }
      else return (0);

  - platform: template
    id: post_wake_poll_time
    name: "Post wake poll time"
    icon: mdi:timelapse
    min_value: 0
    max_value: 1000
    mode: box
    step: 1
    restore_value: true
    initial_value: 300
    optimistic: true
    disabled_by_default: true
    entity_category: config
    on_value:
      - lambda: |-
          ESP_LOGW("Test", "New value %f", x);
          id(tesla_ble_vehicle_id)->post_wake_poll_time_ = x * 1000;
  - platform: template
    id: poll_data_period
    name: "Poll data period"
    icon: mdi:timer-outline
    min_value: 0
    max_value: 1000
    mode: box
    step: 1
    restore_value: true
    initial_value: 60
    optimistic: true
    disabled_by_default: true
    entity_category: config
    on_value:
      - lambda: |-
          ESP_LOGW("Test", "New value %f", x);
          id(tesla_ble_vehicle_id)->poll_data_period_ = x * 1000;
  - platform: template
    id: poll_asleep_period
    name: "Poll asleep period"
    icon: mdi:bed-clock
    min_value: 0
    max_value: 1000
    mode: box
    step: 1
    restore_value: true
    initial_value: 60
    optimistic: true
    disabled_by_default: true
    entity_category: config
    on_value:
      - lambda: |-
          ESP_LOGW("Test", "New value %f", x);
          id(tesla_ble_vehicle_id)->poll_asleep_period_ = x * 1000;
  - platform: template
    id: poll_charging_period
    name: "Poll charging period"
    icon: mdi:timer-sync-outline
    min_value: 0
    max_value: 1000
    mode: box
    step: 1
    restore_value: true
    initial_value: 10
    optimistic: true
    disabled_by_default: true
    entity_category: config
    on_value:
      - lambda: |-
          ESP_LOGW("Test", "New value %f", x);
          id(tesla_ble_vehicle_id)->poll_charging_period_ = x * 1000;
  - platform: template
    id: ble_disconnected_min_time
    name: "BLE disconnected min time"
    icon: mdi:bluetooth-connect
    min_value: 0
    max_value: 1000
    mode: box
    step: 1
    restore_value: true
    initial_value: 300
    optimistic: true
    disabled_by_default: true
    entity_category: config
    on_value:
      - lambda: |-
          ESP_LOGW("Test", "New value %f", x);
          id(tesla_ble_vehicle_id)->ble_disconnected_min_time_ = x * 1000;
  - platform: template
    id: fast_poll_if_unlocked
    name: "Fast poll if unlocked"
    icon: mdi:car-door-lock-open
    min_value: 0
    max_value: 1
    mode: box
    step: 1
    restore_value: true
    initial_value: 1
    optimistic: true
    disabled_by_default: true
    entity_category: config
    on_value:
      - lambda: |-
          ESP_LOGW("Test", "New value %f", x);
          id(tesla_ble_vehicle_id)->fast_poll_if_unlocked_ = x; // Not mS
