substitutions:
  ble_mac_address: !secret ble_mac_address
  tesla_vin: !secret tesla_vin
  charging_amps_max: "32"

ble_client:
  - mac_address: $ble_mac_address
    id: ble_tesla_id

tesla_ble_vehicle:
  ble_client_id: ble_tesla_id
  id: tesla_ble_vehicle_id
  vin: $tesla_vin
  update_interval: 1min # default
  post_wake_poll_time: 300 # How long to poll for data after car awakes (s)
  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
  poll_asleep_period: 60 # Period to poll for data when asleep (s)
  poll_charging_period: 2 # Period to poll for data when charging (s)
  ble_disconnected_min_time: 10 # Minimum time BLE must be disconnected before sensors are Unknwon (s)

  is_asleep:
    name: "Asleep"
  is_user_present:
    name: "User presence"
  is_unlocked:
    name: "Doors"
  is_charge_flap_open:
    id: "is_charge_flap_open"
    name: "Charge flap"
  is_boot_open:
    id: "is_boot_open"
    name: "Boot"
  is_frunk_open:
    id: "is_frunk_open"
    name: "Frunk"
  shift_state:
    name: "Shift state"
  charge_state:
    id: "charge_state"
    name: "Charge level"
  odometer:
    name: "Odometer"
    filters:
      - multiply: 0.01 # Odometer is in hundredths of a mile (can use this to convert to km)
  charge_current:
    name: "Charge current"
  charge_power:
    name: "Charge power"
  max_soc:
    id: "max_soc"
    name: "Charge limit"
  max_amps:
    id: "max_amps"
    name: "Current limit"
  battery_range:
    name: "Range"
  charging_state:
    name: "Charging state"
  last_update:
    name: "Last update"
  is_climate_on:
    id: "is_climate_on"
    name: "Climate"
  internal_temp:
    name: "Interior"
  external_temp:
    name: "Exterior"
      
button:
  - platform: template
    id: ble_pair
    name: Pair BLE key
    icon: mdi:key-wireless
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->startPair();
    entity_category: diagnostic

  - platform: template
    name: Wake up
    icon: mdi:sleep-off
    on_press:
    - lambda: id(tesla_ble_vehicle_id)->wakeVehicle();

  - platform: template
    name: Flash light
    icon: mdi:car-light-high
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage (FLASH_LIGHT, 0);

  - platform: template
    name: Sound horn
    icon: mdi:bugle
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage (SOUND_HORN, 0);

  - platform: template
    name: Frunk
    icon: mdi:car
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->sendVCSECClosureMoveRequestMessage (VCSEC_ClosureMoveRequest_frontTrunk_tag, VCSEC_ClosureMoveType_E_CLOSURE_MOVE_TYPE_OPEN);
  
  - platform: template
    name: Unlock charge port
    icon: mdi:ev-plug-ccs2
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->sendVCSECClosureMoveRequestMessage (VCSEC_ClosureMoveRequest_chargePort_tag, VCSEC_ClosureMoveType_E_CLOSURE_MOVE_TYPE_OPEN);

  - platform: template
    name: Regenerate key
    icon: mdi:key-change
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->regenerateKey();
    entity_category: diagnostic
    disabled_by_default: true

  - platform: template
    name: Force data update
    icon: mdi:database-sync
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->enqueueVCSECInformationRequest(true);
    entity_category: diagnostic

sensor:
  - platform: ble_client
    type: rssi
    ble_client_id: ble_tesla_id
    name: "BLE Signal"
    icon: mdi:bluetooth
    update_interval: 60s
    entity_category: diagnostic

switch:
  - platform: template
    name: "Charger"
    optimistic: true
    icon: mdi:lightning-bolt
    assumed_state: true # we can't read the state of the charger over
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_CHARGING_SWITCH, 1);
    turn_off_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_CHARGING_SWITCH, 0);

  - platform: template
    name: "Sentry mode"
    optimistic: true
    icon: mdi:record-circle-outline
    assumed_state: true # we can't read the state 
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_SENTRY_SWITCH, 1);
    turn_off_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_SENTRY_SWITCH, 0);
  
  - platform: template
    name: "Climate"
    optimistic: true
    icon: mdi:fan
    lambda: |-
      if (id(is_climate_on).state) {
        return true;
      } else {
        return false;
      }
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_HVAC_SWITCH, 1);
    turn_off_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_HVAC_SWITCH, 0);

  - platform: template
    name: "Steering wheel heat"
    optimistic: true
    icon: mdi:steering
    assumed_state: true # we can't read the state 
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_HVAC_STEERING_HEATER_SWITCH, 1);
    turn_off_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_HVAC_STEERING_HEATER_SWITCH, 0);
  
  - platform: template
    name: "Charge port"
    optimistic: true
    icon: mdi:ev-plug-ccs2
    lambda: |-
      if (id(is_charge_flap_open).state) {
        return true;
      } else {
        return false;
      }
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_OPEN_CHARGE_PORT_DOOR,1);
    turn_off_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_CLOSE_CHARGE_PORT_DOOR,1);

  - platform: template
    name: "Vent"
    optimistic: true
    icon: mdi:car-door
    assumed_state: true # we can't read the state 
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_WINDOWS_SWITCH,1);
    turn_off_action:
      - lambda: id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_WINDOWS_SWITCH,0);

  - platform: template
    name: "Boot"
    optimistic: true
    icon: mdi:car-back
    lambda: |-
      if (id(is_boot_open).state) {
        return true;
      } else {
        return false;
      }
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: id(tesla_ble_vehicle_id)->sendVCSECClosureMoveRequestMessage (VCSEC_ClosureMoveRequest_rearTrunk_tag, VCSEC_ClosureMoveType_E_CLOSURE_MOVE_TYPE_OPEN);
    turn_off_action:
      - lambda: id(tesla_ble_vehicle_id)->sendVCSECClosureMoveRequestMessage (VCSEC_ClosureMoveRequest_rearTrunk_tag, VCSEC_ClosureMoveType_E_CLOSURE_MOVE_TYPE_CLOSE);
      
  - platform: ble_client
    ble_client_id: ble_tesla_id
    name: "BLE Connection"
    entity_category: diagnostic

number:
  - platform: template
    name: "Charging amps"
    id: charging_amps
    icon: mdi:ev-station
    unit_of_measurement: "A"
    mode: slider
    update_interval: 2s
    min_value: 0
    max_value: $charging_amps_max
    step: 1
    set_action:
      - lambda: |-
          int var_x = static_cast<int>(x);
          id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_CHARGING_AMPS, var_x);
    lambda: |-
      if (id(max_amps).has_state())
      {
        return id(max_amps).state;
      }
      else return (0); 
  - platform: template
    name: "Charging limit"
    id: charging_limit
    icon: mdi:ev-station
    unit_of_measurement: "%"
    mode: slider
    update_interval: 2s
    min_value: 50
    max_value: 100
    step: 1
    set_action:
      - lambda: |-
          int var_x = static_cast<int>(x);
          id(tesla_ble_vehicle_id)->sendCarServerVehicleActionMessage(SET_CHARGING_LIMIT, var_x);
    lambda: |-
      if (id(max_soc).has_state())
      {
        return id(max_soc).state;
      }
      else return (0); 
        
